# Generated by Django 3.2.10 on 2022-11-12 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
                ('course_number', models.IntegerField(default=0)),
                ('semester_code', models.IntegerField(default=0)),
                ('course_section', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('catalog_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('class_capacity', models.IntegerField(default=0)),
                ('waitlist', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('days', models.CharField(max_length=100)),
                ('start_time', models.CharField(default=None, max_length=100)),
                ('end_time', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='classes', to='louslistapp.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='louslistapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='louslistapp.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='louslistapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='louslistapp.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='louslistapp.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='louslistapp.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
