# Generated by Django 4.1.2 on 2022-11-07 06:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
                ('course_number', models.IntegerField(default=0)),
                ('semester_code', models.IntegerField(default=0)),
                ('course_section', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('catalog_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('class_capacity', models.IntegerField(default=0)),
                ('waitlist', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('days', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Schedule 1', max_length=100)),
                ('courses', models.ManyToManyField(blank=True, related_name='schedules', to='louslistapp.course')),
                ('schedule_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ManyToManyField(to='louslistapp.course')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
