# Generated by Django 3.2.10 on 2022-10-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('className', models.CharField(blank=True, max_length=50)),
                ('professor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
