# Generated by Django 4.1.2 on 2022-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
