# Generated by Django 3.2.10 on 2022-11-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
