# Generated by Django 3.2.10 on 2022-10-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='className',
            new_name='catalog_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='professor_name',
        ),
        migrations.AddField(
            model_name='course',
            name='class_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_section',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_avail',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_code',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='wait_cap',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='wait_list',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
