# Generated by Django 3.2.10 on 2022-11-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
