# Generated by Django 3.2.10 on 2022-10-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0002_auto_20221020_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='component',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
