# Generated by Django 4.0.3 on 2022-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0002_auto_20221113_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1500, null=True)),
                ('author', models.CharField(max_length=1500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='louslistapp.comment'),
        ),
    ]
