# Generated by Django 3.2.10 on 2022-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0002_alter_course_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
