# Generated by Django 3.2.10 on 2022-10-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0003_course_component'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
