# Generated by Django 3.2.10 on 2022-10-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('louslistapp', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
                ('course_number', models.IntegerField(default=0)),
                ('semester_code', models.IntegerField(default=0)),
                ('course_section', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('catalog_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('class_capacity', models.IntegerField(default=0)),
                ('wait_list', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('days', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
