# Generated by Django 3.2.10 on 2022-10-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_email', models.CharField(max_length=100)),
            ],
        ),
    ]
