# Generated by Django 3.2.10 on 2022-11-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0006_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='wait_list',
            new_name='waitlist',
        ),
    ]
