# Generated by Django 3.2.10 on 2022-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0008_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(related_name='schedules', to='louslistapp.Course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Schedule 1', max_length=100),
        ),
    ]
