# Generated by Django 3.2.10 on 2022-11-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0009_auto_20221105_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='louslistapp.Course'),
        ),
    ]
