# Generated by Django 3.2.10 on 2022-11-06 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('louslistapp', '0010_auto_20221105_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='credits',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
