# Generated by Django 3.2.10 on 2022-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0012_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
