# Generated by Django 3.2.10 on 2022-11-07 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0013_course_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
