# Generated by Django 3.2.10 on 2022-11-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0014_account'),
        ('louslistapp', '0014_auto_20221106_2027'),
    ]

    operations = [
    ]
