# Generated by Django 3.2.10 on 2022-11-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslistapp', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='this is my bio'),
        ),
    ]
